# .achecker.yml
ruleArchive: latest
policies:
  - WCAG_2_2
failLevels:
  - violation
reportLevels:
  - violation
  - potentialviolation
outputFormat:
  - json
  - html
outputFolder: accessibility-reports
puppeteerArgs:
  - --no-sandbox
  - --disable-setuid-sandbox