baseURL = "https://ashford-wide.pages.dev"
locale = "en-GB"
title = "Ashford Wide"
publishDir = "public"
paginate = 9
buildDrafts = false
buildFuture = true
enableRobotsTXT = true
disableHugoGeneratorInject = true

[params]
  legalName = "Ashford Wide"
  description = "Working together for a better Ashford"
  showRemembrance = true
  logo = "/images/aw-logo.png"
  email = "community@ashfordwide.com"
  businessEmail = "business@ashfordwide.com"
  ogImage = "/images/og-default.jpg"
  foundingDate = 2012
  companyNumber = ""
  activePromo = "business-network-event"
  featuredVideoID = "1180234252"
  featuredVideoTitle = "Ashford Wide - putting up Poppies & Flags for Remembrance"
  googleSiteVerification = "GOOGLE_CODE"
  facebookDomainVerification = "FACEBOOK_CODE"
  bingDomainVerification = "BING_CODE"
  facebook = "https://www.facebook.com/AshfordWide"
  twitter = "https://x.com/AshfordWide"
  instagram = "https://www.instagram.com/ashfordwide"
  linkedin = ""
  googleBusinessProfile = ""

[security]
  [security.node]
    [security.node.permissions]
      allowAddons = ["tailwindcss", "postcss"]
      allowWorker = ["tailwindcss", "postcss"]
      allowChildProcess = ["tailwindcss", "postcss"]

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.youTube]
    disable = true
    privacyEnhanced = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false

[permalinks]
  [permalinks.page]
    news = "/news/:contentbasename/"
    events = "/events/:contentbasename/"