baseURL = "https://ashford-wide.pages.dev"
languageCode = "en-GB"
title = "Ashford Wide"
publishDir = "public"
paginate = 9
buildDrafts = false
buildFuture = true
enableRobotsTXT = true
disableHugoGeneratorInject = true

[params]
  legalName = "Ashford Wide"
  description = "Working together for a better Ashford"
  tagline = "Working together for a better Ashford"
  showRemembrance = false
  logo = "/images/aw-logo.png"
  email = "community@ashfordwide.com"
  businessEmail = "business@ashfordwide.com"
  ogImage = "/images/og-default.jpg"
  foundedYear = 2012
  companyNumber = ""
  activePromo = "best-dressed-window"
  googleSiteVerification = "GOOGLE_CODE"
  facebookDomainVerification = "FACEBOOK_CODE"
  bingDomainVerification = "BING_CODE"
  facebook = "https://www.facebook.com/AshfordWide"
  twitter = "https://twitter.com/AshfordWide"
  instagram = "https://www.instagram.com/ashfordwide"
  linkedin = ""

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.instagram]
    simple = true

[permalinks]
  [permalinks.page]
    news = "/news/:contentbasename/"
    events = "/events/:contentbasename/"